/**
 * MSN-2980 — Category-photo mapping.
 *
 * Wikimedia Commons is FORBIDDEN per chairman mandate 2026-08-29. Every
 * photo URL in this file now points at:
 *   - Self-hosted hero images (Flickr + Unsplash originals downloaded
 *     into /public/photos/originals/, then WebP Q70 + AVIF Q50 s=4
 *     variants generated at 640/1080/1920/3840w).
 *   - Flickr live.staticflickr.com URLs (CC BY family — attribution
 *     compiled in `photoCreditFor()`).
 *   - Unsplash CDN images.unsplash.com URLs (CC0 — Unsplash licence).
 *
 * The per-page KUBE pattern is "image + label only" — body copy lives
 * on the deep pages, never on the cards. This file powers:
 *   - 9 hero images (one per category page)
 *   - 6 homepage tiles
 *   - 12 category cards on /things-to-do
 *   - About brand-statement masthead
 *
 * Attribution block is rendered at /photo-credits.
 */

export type KubePhoto = {
  /** Caption / descriptive alt text — must read as a complete sentence. */
  caption: string;
  /**
   * Image URL.
   *   - For self-hosted hero images: `/photos/hero-{slug}-{w}w.webp`
   *     (the 1920w default is used as `url`, with AVIF variants served
   *     through `srcSet`).
   *   - For inline / card images: a Flickr or Unsplash URL — the
   *     Cloudflare Pages next/image config has these hosts in
   *     `remotePatterns`, so next/image will pass the URL through.
   */
  url: string;
  /**
   * Optional responsive `srcset` value. When present, the consuming
   * next/image component passes it through verbatim (Next.js does NOT
   * regenerate srcset for these — the files are already pre-sized).
   */
  srcSet?: string;
  /** Author attribution (for the credit line). */
  author: string;
  /** Licence — CC BY / CC BY-NC / CC BY-NC-SA / CC0 (Unsplash) etc. */
  licence: string;
  /** Optional Commons / Flickr / Unsplash page link for credit back-link. */
  sourcePage?: string;
};

/**
 * Build the responsive `srcSet` for a self-hosted hero AVIF. The
 * widths (640 / 1080 / 1920 / 3840) mirror the variants generated by
 * the MSN-2980 image pull pipeline (see `scripts/msn2980/pull_heroes.py`).
 */
export function heroWebpSrcSet(slug: string): string {
  return [
    `/photos/hero-${slug}-640w.avif 640w`,
    `/photos/hero-${slug}-1080w.avif 1080w`,
    `/photos/hero-${slug}-1920w.avif 1920w`,
    `/photos/hero-${slug}-3840w.avif 3840w`,
  ].join(", ");
}

/** The default hero image URL — 1920w WebP at Q70. */
export function heroWebpUrl(slug: string): string {
  return `/photos/hero-${slug}-1920w.webp`;
}

/** Build a card image srcSet from a slug in /public/photos/cards/. */
export function cardWebpSrcSet(slug: string): string {
  return `/photos/cards/card-${slug}-1280w.avif 1280w`;
}

export function cardWebpUrl(slug: string): string {
  return `/photos/cards/card-${slug}-1280w.webp`;
}

export type CategoryPhotos = {
  hero: KubePhoto;
  inline: KubePhoto[];
};

/* ----------------------------------------------------------------------
 * Hero images — 1 per category, picked by visual fit to the topic.
 * Every URL is now self-hosted (downloaded from Flickr/Unsplash per
 * Albert's IMAGE_MANIFEST.md, all non-Wikimedia).
 * -------------------------------------------------------------------- */

const HERO = {
  surf: {
    caption: "A surfer riding a Noosa wave at sunrise — the live conditions we link to on /surf-and-weather.",
    url: heroWebpUrl("surf-and-weather"),
    srcSet: heroWebpSrcSet("surf-and-weather"),
    author: "Flickr (Openverse) — 'I roar for my supper'",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/8029/8052945119_e3f2edce31_b.jpg",
  },
  noosaNationalPark: {
    caption: "Noosa National Park Granite Bay — no dogs, no buildings, the coastal walk at its most dramatic.",
    url: heroWebpUrl("noosa-national-park"),
    srcSet: heroWebpSrcSet("noosa-national-park"),
    author: "Flickr (Openverse) — 'Noosa National Park Granite Bay'",
    licence: "CC BY",
    sourcePage: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
  },
  accommodation: {
    caption: "South Pacific Resort, Noosa — apartment-style accommodation with a pool, near Hastings Street.",
    url: heroWebpUrl("accommodation"),
    srcSet: heroWebpSrcSet("accommodation"),
    author: "Flickr (Openverse) — 'South Pacific Resort, Noosa'",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/2090/2447049260_2a8189d4d6_b.jpg",
  },
  thingsToDo: {
    caption: "The Noosa River at Noosaville — paddleboard, kayak, and ferry water, framed by the gum trees.",
    url: heroWebpUrl("things-to-do"),
    srcSet: heroWebpSrcSet("things-to-do"),
    author: "Flickr (Openverse) — 'Shiny afternoon' (Noosa River)",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/8330/8146977124_491b4d5696.jpg",
  },
  fishingReports: {
    caption: "Morning on the Noosa River — the principal recreational fishing water for the shire.",
    url: heroWebpUrl("fishing-reports"),
    srcSet: heroWebpSrcSet("fishing-reports"),
    author: "Flickr (Openverse) — 'Morning on the Noosa River'",
    licence: "CC0",
    sourcePage: "https://live.staticflickr.com/65535/9572462197_6879fe750b_b.jpg",
  },
  boatsAndWatercraft: {
    caption: "Kayaks on a calm river reach — the hire-watercraft most visitors start with at Noosa.",
    url: heroWebpUrl("boats-and-watercraft"),
    srcSet: heroWebpSrcSet("boats-and-watercraft"),
    author: "Flickr (Openverse) — 'Brisbane River kayaks'",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/2114/2203239982_0f8f4f3d74_b.jpg",
  },
  travelAndTransport: {
    caption: "A quiet coastal road — the kind of approach into Noosa that the hinterland road-trips pass through.",
    url: heroWebpUrl("travel-and-transport"),
    srcSet: heroWebpSrcSet("travel-and-transport"),
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a",
  },
  webcams: {
    caption: "A long coastal view at midday — the angle most public webcams capture from the Noosa headland.",
    url: heroWebpUrl("webcams"),
    srcSet: heroWebpSrcSet("webcams"),
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1559827260-dc66d52bef19",
  },
} as const;

/* ----------------------------------------------------------------------
 * Inline images — 4 per category, all non-Wikimedia.
 * Each is placed between body sections in render order.
 * -------------------------------------------------------------------- */

const INLINE = {
  surf: [
    {
      caption: "Surfer paddling out at Noosa Main Beach at dawn.",
      url: "https://live.staticflickr.com/3545/3488069272_d764c72594_b.jpg",
      author: "Flickr (Openverse) — 'Me surfing in Noosa'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/3545/3488069272_d764c72594_b.jpg",
    },
    {
      caption: "Generic ocean wave — used for the surf tile on the homepage (live data overlays).",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    {
      caption: "Generic sky / wind scene — used for the wind tile.",
      url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1502082553048-f009c37129b9",
    },
    {
      caption: "Noosa Main Beach in storm light — the swell window when the south-east wraps.",
      url: "https://live.staticflickr.com/3757/11681350584_c78a09d814_b.jpg",
      author: "Flickr (Openverse) — 'Noosa Main Beach, storm out to sea'",
      licence: "CC BY-NC-ND",
      sourcePage: "https://live.staticflickr.com/3757/11681350584_c78a09d814_b.jpg",
    },
  ],
  noosaNationalPark: [
    {
      caption: "Fairy Pool — the freshwater swim spot reached via the Tanglewood track.",
      url: "https://live.staticflickr.com/7902/46389696594_be050f6b5a_b.jpg",
      author: "Flickr (Openverse) — 'Noosa National Park Fairy Pool'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7902/46389696594_be050f6b5a_b.jpg",
    },
    {
      caption: "Tea Tree Cove — the first sheltered beach south of the headland.",
      url: "https://live.staticflickr.com/2420/2153303691_b1d994393b_b.jpg",
      author: "Flickr (Openverse) — 'Tea Tree Cove, Noosa National Park'",
      licence: "CC BY-SA",
      sourcePage: "https://live.staticflickr.com/2420/2153303691_b1d994393b_b.jpg",
    },
    {
      caption: "Hell's Gates and Alexandria Bay — the clothing-optional beach at the southern end of the coastal walk.",
      url: "https://live.staticflickr.com/8125/15648131978_aef5f2d88f_b.jpg",
      author: "Flickr (Openverse) — 'Hells Gates and Alexandria Bay'",
      licence: "CC BY-NC-SA",
      sourcePage: "https://live.staticflickr.com/8125/15648131978_aef5f2d88f_b.jpg",
    },
    {
      caption: "Noosa rainforest — used for the Tanglewood walk deep page.",
      url: "https://live.staticflickr.com/289/20066708795_71c95dc51a_b.jpg",
      author: "Flickr (Openverse) — 'Noosa rainforest'",
      licence: "CC BY-NC-ND",
      sourcePage: "https://live.staticflickr.com/289/20066708795_71c95dc51a_b.jpg",
    },
  ],
  accommodation: [
    {
      caption: "Castaways Resort & Spa, Mission Beach — fallback for the Sofitel card (no Noosa-specific Sofitel photo is non-Wikimedia).",
      url: "https://live.staticflickr.com/7195/6804500540_84424cfb73_b.jpg",
      author: "Flickr (Openverse) — 'Castaways Resort & Spa, Mission Beach'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7195/6804500540_84424cfb73_b.jpg",
    },
    {
      caption: "Hamilton Island swimming pool — fallback for the RACV card.",
      url: "https://live.staticflickr.com/1421/705740732_3a50d37015.jpg",
      author: "Flickr (Openverse) — 'Hamilton Island Swimming Pool'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/1421/705740732_3a50d37015.jpg",
    },
    {
      caption: "Sunshine Beach, Noosa — used for the Sunshine Beach Resort card.",
      url: "https://live.staticflickr.com/1408/705933988_e7ab226bb2.jpg",
      author: "Flickr (Openverse) — 'Sunshine Beach, Noosa'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/1408/705933988_e7ab226bb2.jpg",
    },
    {
      caption: "Netanya — generic Hastings Street apartments fallback.",
      url: "https://live.staticflickr.com/6231/6224415039_628e2eb0a1_b.jpg",
      author: "Flickr (Openverse) — 'Noosa'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/6231/6224415039_628e2eb0a1_b.jpg",
    },
  ],
  thingsToDo: [
    {
      caption: "River Crossing — generic calm-water river scene used for the river-experience card.",
      url: "https://live.staticflickr.com/7261/13940326252_74135d0576_b.jpg",
      author: "Flickr (Openverse) — 'River Crossing'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7261/13940326252_74135d0576_b.jpg",
    },
    {
      caption: "Generic restaurant dining — used for the eat-experience card.",
      url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    },
    {
      caption: "P1017550 — generic boat scene used for the cruise/tour card.",
      url: "https://live.staticflickr.com/7068/13438728693_e10c56cced.jpg",
      author: "Flickr (Openverse) — 'P1017550'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7068/13438728693_e10c56cced.jpg",
    },
    {
      caption: "Noosa River and Gympie Terrace, Noosaville (c. 1940) — historical context.",
      url: "https://live.staticflickr.com/65535/54849508625_d3595b783b_b.jpg",
      author: "Flickr (Openverse) — Public Domain Mark",
      licence: "PDM",
      sourcePage: "https://live.staticflickr.com/65535/54849508625_d3595b783b_b.jpg",
    },
  ],
  fishingReports: [
    {
      caption: "Noosa Everglades — the upper-river fishing water.",
      url: "https://live.staticflickr.com/3696/12046547304_e4e4449777_b.jpg",
      author: "Flickr (Openverse) — 'Noosa Everglades, Australia'",
      licence: "CC0",
      sourcePage: "https://live.staticflickr.com/3696/12046547304_e4e4449777_b.jpg",
    },
    {
      caption: "Boat at river mouth — the boat-based fishing launch.",
      url: "https://live.staticflickr.com/7068/13438728693_e10c56cced.jpg",
      author: "Flickr (Openverse) — 'P1017550'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7068/13438728693_e10c56cced.jpg",
    },
    {
      caption: "Noosa River at low tide — the flathead water.",
      url: "https://live.staticflickr.com/3696/12046547304_e4e4449777_b.jpg",
      author: "Flickr (Openverse)",
      licence: "CC0",
      sourcePage: "https://live.staticflickr.com/3696/12046547304_e4e4449777_b.jpg",
    },
    {
      caption: "Noosa main beach — the surf-side fishing gutter.",
      url: "https://live.staticflickr.com/8240/8531818425_4f7d65d9e6.jpg",
      author: "Flickr (Openverse) — 'Noosa Main Beach / Hastings Street looking west'",
      licence: "CC BY-NC-SA",
      sourcePage: "https://live.staticflickr.com/8240/8531818425_4f7d65d9e6.jpg",
    },
  ],
  boatsAndWatercraft: [
    {
      caption: "Stand-up paddleboard — the hire-craft on the river.",
      url: "https://live.staticflickr.com/7101/13941478461_d01edfaa11_b.jpg",
      author: "Flickr (Openverse)",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7101/13941478461_d01edfaa11_b.jpg",
    },
    {
      caption: "River ferry — waterborne transport between Hastings and Noosaville.",
      url: "https://live.staticflickr.com/7261/13940326252_74135d0576_b.jpg",
      author: "Flickr (Openverse) — 'River Crossing'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7261/13940326252_74135d0576_b.jpg",
    },
    {
      caption: "Noosa River — kayak rental water.",
      url: "https://live.staticflickr.com/2114/2203239982_0f8f4f3d74_b.jpg",
      author: "Flickr (Openverse)",
      licence: "CC BY-NC-SA",
      sourcePage: "https://live.staticflickr.com/2114/2203239982_0f8f4f3d74_b.jpg",
    },
    {
      caption: "Generic travel scene — used for travel-and-transport.",
      url: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1505142468610-359e7d316be0",
    },
  ],
  travelAndTransport: [
    {
      caption: "Australian coast road — the drive into Noosa.",
      url: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a",
    },
    {
      caption: "Generic travel scene.",
      url: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1505142468610-359e7d316be0",
    },
    {
      caption: "Australian coastal approach.",
      url: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a",
    },
    {
      caption: "Boat at river mouth — the ferry approach.",
      url: "https://live.staticflickr.com/7068/13438728693_e10c56cced.jpg",
      author: "Flickr (Openverse) — 'P1017550'",
      licence: "CC BY",
      sourcePage: "https://live.staticflickr.com/7068/13438728693_e10c56cced.jpg",
    },
  ],
  webcams: [
    {
      caption: "Coastal view placeholder.",
      url: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1542401886-65d6c61db217",
    },
    {
      caption: "Coastal view placeholder.",
      url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1600&q=80",
      author: "Unsplash CDN",
      licence: "CC0 (Unsplash)",
      sourcePage: "https://images.unsplash.com/photo-1559827260-dc66d52bef19",
    },
    {
      caption: "Noosa main beach — the angle most webcams approximate.",
      url: "https://live.staticflickr.com/8240/8531818425_4f7d65d9e6.jpg",
      author: "Flickr (Openverse)",
      licence: "CC BY-NC-SA",
      sourcePage: "https://live.staticflickr.com/8240/8531818425_4f7d65d9e6.jpg",
    },
    {
      caption: "Noosa headland view.",
      url: "https://live.staticflickr.com/8514/8532929182_a1ea8ef7be.jpg",
      author: "Flickr (Openverse) — 'Noosa Main Beach / Hastings Street looking east'",
      licence: "CC BY-NC-SA",
      sourcePage: "https://live.staticflickr.com/8514/8532929182_a1ea8ef7be.jpg",
    },
  ],
} as const;

export const CATEGORY_PHOTOS: Record<string, CategoryPhotos> = {
  "surf-and-weather": { hero: HERO.surf, inline: [...INLINE.surf] },
  "noosa-national-park": {
    hero: HERO.noosaNationalPark,
    inline: [...INLINE.noosaNationalPark],
  },
  accommodation: { hero: HERO.accommodation, inline: [...INLINE.accommodation] },
  "things-to-do": { hero: HERO.thingsToDo, inline: [...INLINE.thingsToDo] },
  "fishing-reports": {
    hero: HERO.fishingReports,
    inline: [...INLINE.fishingReports],
  },
  "boats-and-watercraft": {
    hero: HERO.boatsAndWatercraft,
    inline: [...INLINE.boatsAndWatercraft],
  },
  "travel-and-transport": {
    hero: HERO.travelAndTransport,
    inline: [...INLINE.travelAndTransport],
  },
  webcams: { hero: HERO.webcams, inline: [...INLINE.webcams] },
};

/* ----------------------------------------------------------------------
 * Homepage hero — MSN-2980.
 *
 * KUBE pattern: 100vh full-bleed, dark overlay, large serif headline,
 * no body copy on the hero. Source: Albert's verified Flickr photo.
 * -------------------------------------------------------------------- */

export const HOMEPAGE_HERO: KubePhoto = {
  caption:
    "Sunset over Noosa Main Beach — headland silhouette and palm frond.",
  url: heroWebpUrl("home"),
  srcSet: heroWebpSrcSet("home"),
  author: "Flickr (Openverse) — 'Noosa Main Beach Silhouette'",
  licence: "CC BY",
  sourcePage: "https://live.staticflickr.com/3664/3487547682_52b62b9b03_b.jpg",
};

/* ----------------------------------------------------------------------
 * MSN-2980 — six image-led homepage tiles (KUBE atmospheric hooks).
 *
 * Per KUBE pattern: image + label only. NO body copy on the cards.
 * Body copy lives on the deep pages. Each photo URL is verified on
 * Flickr (Openverse) or Unsplash — all non-Wikimedia.
 * -------------------------------------------------------------------- */

export const HOME_TILES = {
  /** Strongest commercial — Hastings Street / Main Beach silhouette. */
  whereToStay: {
    caption:
      "Noosa Main Beach / Hastings Street looking west — the walk from a Hastings Street hotel to Main Beach.",
    url: "https://live.staticflickr.com/8240/8531818425_4f7d65d9e6.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/8240/8531818425_4f7d65d9e6.jpg",
  },
  /** Noosa River — paddle / kayak / ferry water. */
  thingsToDo: {
    caption:
      "The Noosa River at Noosaville, looking downstream — paddleboard and kayak water.",
    url: "https://live.staticflickr.com/8330/8146977124_491b4d5696.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/8330/8146977124_491b4d5696.jpg",
  },
  /** Beaches & nature — headland view from the coastal walk. */
  beachesAndNature: {
    caption:
      "The Noosa headland and the river mouth — the coastal walk's signature view.",
    url: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
    author: "Flickr (Openverse) — 'Noosa National Park Granite Bay'",
    licence: "CC BY",
    sourcePage: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
  },
  /** Eat & drink — Hastings Street atmospheric. */
  eatAndDrink: {
    caption:
      "People watching people at Aroma, Hastings Street, Noosa.",
    url: "https://live.staticflickr.com/615/31910895645_d321ec9068_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/615/31910895645_d321ec9068_b.jpg",
  },
  /** Plan your trip — Noosa Ferry, river-borne transport. */
  planYourTrip: {
    caption:
      "A river crossing — waterborne transport between Hastings Street and Noosaville.",
    url: "https://live.staticflickr.com/7261/13940326252_74135d0576_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY",
    sourcePage: "https://live.staticflickr.com/7261/13940326252_74135d0576_b.jpg",
  },
  /** Today in Noosa — Main Beach on a sunny day. */
  todayInNoosa: {
    caption:
      "Noosa Main Beach — the live surf and weather destination for the homepage live strip.",
    url: "https://live.staticflickr.com/8029/8052945119_e3f2edce31_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/8029/8052945119_e3f2edce31_b.jpg",
  },
} as const;

/** Inspirational feature image — granite headland + boardwalk. */
export const FEATURE_IMAGE: KubePhoto = {
  caption:
    "Granite headland and the river mouth — the coastal walk's signature view.",
  url: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
  author: "Flickr (Openverse) — 'Noosa National Park Granite Bay'",
  licence: "CC BY",
  sourcePage: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
};

/* ----------------------------------------------------------------------
 * MSN-2980 — twelve /things-to-do category images (KUBE cards).
 *
 * One image per category card, mapped to the D2 category list. All
 * URLs are verified on Flickr (Openverse) or Unsplash — non-Wikimedia.
 * -------------------------------------------------------------------- */

export const CATEGORY_CARD_PHOTOS = {
  bestBeaches: {
    caption: "Noosa Main Beach at midday — the patrolled swimming beach at the bottom of Hastings Street.",
    url: "https://live.staticflickr.com/3664/3487547682_52b62b9b03_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY",
    sourcePage: "https://live.staticflickr.com/3664/3487547682_52b62b9b03_b.jpg",
  },
  walksAndNature: {
    caption: "The Noosa headland coastal walk — granite boulders, tallowwood forest, the surf below.",
    url: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
    author: "Flickr (Openverse) — 'Noosa National Park Granite Bay'",
    licence: "CC BY",
    sourcePage: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
  },
  riverAdventures: {
    caption: "The Noosa River at Noosaville — kayak and paddleboard water.",
    url: "https://live.staticflickr.com/8330/8146977124_491b4d5696.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/8330/8146977124_491b4d5696.jpg",
  },
  foodAndDrink: {
    caption: "People watching at Aroma, Hastings Street — the headland end of Noosa Main Beach.",
    url: "https://live.staticflickr.com/615/31910895645_d321ec9068_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/615/31910895645_d321ec9068_b.jpg",
  },
  surfingAndWaterSports: {
    caption: "Surfer riding a Noosa wave at sunrise — the live surf we link out to.",
    url: "https://live.staticflickr.com/8029/8052945119_e3f2edce31_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/8029/8052945119_e3f2edce31_b.jpg",
  },
  familyActivities: {
    caption: "Generic outdoor activity — used for the family-activity card.",
    url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1502082553048-f009c37129b9",
  },
  wellnessAndRelaxation: {
    caption: "Generic wellness scene — used for the wellness card.",
    url: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1542401886-65d6c61db217",
  },
  marketsAndShopping: {
    caption: "Noosa Farmers Market — Sunday morning on the Noosaville showgrounds.",
    url: "https://live.staticflickr.com/2301/2367573625_8f0fd5692b_b.jpg",
    author: "Flickr (Openverse) — 'Noosa Farmers Market'",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/2301/2367573625_8f0fd5692b_b.jpg",
  },
  dayTrips: {
    caption: "A quiet coastal road — the road-trip mode into the Noosa Hinterland.",
    url: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a",
  },
  rainyDay: {
    caption: "Storm light over Noosa Main Beach — the rainy-day walk.",
    url: "https://live.staticflickr.com/3757/11681350584_c78a09d814_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC-ND",
    sourcePage: "https://live.staticflickr.com/3757/11681350584_c78a09d814_b.jpg",
  },
  bookableExperiences: {
    caption: "Stand-up paddleboard — the hire-watercraft most visitors start with.",
    url: "https://live.staticflickr.com/7101/13941478461_d01edfaa11_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY",
    sourcePage: "https://live.staticflickr.com/7101/13941478461_d01edfaa11_b.jpg",
  },
  itineraries: {
    caption: "Sunset over Noosa Beach — the headline image for first-time visitor itineraries.",
    url: "https://live.staticflickr.com/3664/3487547682_52b62b9b03_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY",
    sourcePage: "https://live.staticflickr.com/3664/3487547682_52b62b9b03_b.jpg",
  },
} as const;

/* ----------------------------------------------------------------------
 * /about brand-statement masthead image.
 * -------------------------------------------------------------------- */

export const ABOUT_BRAND_IMAGE: KubePhoto = {
  caption: "The granite headland and the river mouth — viewed from the coastal walk.",
  url: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
  author: "Flickr (Openverse) — 'Noosa National Park Granite Bay'",
  licence: "CC BY",
  sourcePage: "https://live.staticflickr.com/7915/46346554164_176a80477f_b.jpg",
};

/* ----------------------------------------------------------------------
 * MSN-2980 — Shopping (retailer) hero + per-retailer card images.
 * Replaces the 8 repeated generic Wikimedia photos on /shopping.
 * -------------------------------------------------------------------- */

export const SHOPPING_PHOTOS = {
  hero: {
    caption: "Noosa Farmers Market stalls — Sunday morning on the Noosaville showgrounds.",
    url: heroWebpUrl("shopping"),
    srcSet: heroWebpSrcSet("shopping"),
    author: "Flickr (Openverse) — 'Noosa Farmers Market'",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/2301/2367573625_8f0fd5692b_b.jpg",
  },
  noosaFarmersMarket: {
    caption: "Noosa Farmers Market — Sunday morning.",
    url: "https://live.staticflickr.com/2301/2367573625_8f0fd5692b_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/2301/2367573625_8f0fd5692b_b.jpg",
  },
  eumundiMarkets: {
    caption: "Eumundi Markets — the famous Wednesday/Saturday hinterland market.",
    url: "https://live.staticflickr.com/2398/2189844448_ecff21b6d5_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-SA",
    sourcePage: "https://live.staticflickr.com/2398/2189844448_ecff21b6d5_b.jpg",
  },
  noosaRegionalGallery: {
    caption: "Noosa Regional Gallery flyer rack — the cultural stop on Riverside.",
    url: "https://live.staticflickr.com/3490/3983700808_814732b141_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC-SA",
    sourcePage: "https://live.staticflickr.com/3490/3983700808_814732b141_b.jpg",
  },
  // 8 non-deep-card generic categories — Albert's fallback CC0 Unsplash shots.
  junction: {
    caption: "Australian shopping street — generic retail scene for the Junction card.",
    url: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a",
  },
  peregian: {
    caption: "Peregian village — used for the Peregian shopping card.",
    url: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1505142468610-359e7d316be0",
  },
  beachwear: {
    caption: "Beachwear shopping — generic surf-shop scene.",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
  },
  homewares: {
    caption: "Australian homewares — generic retail scene.",
    url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
  },
} as const;

/* ----------------------------------------------------------------------
 * MSN-2980 — Eat & drink photos (kept on /shopping per chairman mandate:
 * "Do not add more written content or new features". The dining cards
 * remain on /shopping alongside the retail cards).
 * -------------------------------------------------------------------- */

export const EAT_DRINK_PHOTOS = {
  hero: {
    caption: "A Hastings Street restaurant table — the dining scene at sunset.",
    url: heroWebpUrl("eat-drink"),
    srcSet: heroWebpSrcSet("eat-drink"),
    author: "Flickr (Openverse) — 'Aroma, Hastings Street'",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/615/31910895645_d321ec9068_b.jpg",
  },
  hastingsStreet: {
    caption: "People watching people at Aroma, Hastings Street, Noosa.",
    url: "https://live.staticflickr.com/615/31910895645_d321ec9068_b.jpg",
    author: "Flickr (Openverse)",
    licence: "CC BY-NC",
    sourcePage: "https://live.staticflickr.com/615/31910895645_d321ec9068_b.jpg",
  },
  diningGeneric: {
    caption: "Generic outdoor dining scene.",
    url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600&q=80",
    author: "Unsplash CDN",
    licence: "CC0 (Unsplash)",
    sourcePage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
  },
} as const;
