/**
 * Category-photo mapping — Sprint 1.5 (MSN-2958 / TSK-2958-02).
 *
 * Maps each of the 8 category pages to the verified Wikimedia Commons
 * photos from Albert's `photo_inventory.md`. Each category gets:
 *   - 1 hero image (full-bleed, ~60vh, captioned)
 *   - 3+ inline images (placed between body sections, captioned + credited)
 *
 * Every URL was resolved live via the Commons API on 2026-08-27. All
 * authors and licences are recorded so the site's `/image-credits/`
 * page (auto-rendered from this file) is always in sync.
 *
 * Hot-link strategy (MSN-2975 perf chunk 2):
 *   - HERO + HOMEPAGE_HERO: served self-hosted as AVIF/WebP variants
 *     generated from the Commons originals and committed under
 *     `public/photos/hero-{slug}-{640,1080,1920,3840}w.webp`. Each
 *     entry carries `url` (1920w default) + `srcSet` (4 widths). This
 *     removes the 9 Wikimedia CDN round-trips for the LCP image on
 *     every page and the homepage hero, freeing up the critical path
 *     for in-page work.
 *   - All other photos (INLINE, HOME_TILES, FEATURE_IMAGE,
 *     CATEGORY_CARD_PHOTOS, ABOUT_BRAND_IMAGE): continue to be
 *     Wikimedia-served 1280-px thumbnails for now. Conversion of the
 *     /things-to-do 9-card grid is deferred to MSN-2975 chunk 5
 *     (see `evidence/MSN-2975/`).
 *
 * `next.config.mjs` includes `upload.wikimedia.org` in `images.remotePatterns`
 * so next/image can transform the remaining Wikimedia URLs. Self-hosted
 * paths under `/photos/...` are served from the same origin so no
 * remotePatterns entry is required for them.
 */

export type WikimediaPhoto = {
  /** Caption / descriptive alt text — must read as a complete sentence. */
  caption: string;
  /**
   * Image URL.
   *   - For self-hosted hero images: `/photos/hero-{slug}-{w}w.webp`
   *     (the 1920w default is used as `url`).
   *   - For Wikimedia-served photos: `https://upload.wikimedia.org/...`
   *     1280-px thumbnail.
   */
  url: string;
  /**
   * Optional responsive `srcset` value. When present, the consuming
   * next/image component passes it through verbatim (Next.js does NOT
   * regenerate srcset for these — the files are already pre-sized).
   *
   * Format: `"/path/img-640w.webp 640w, /path/img-1080w.webp 1080w, ..."`.
   *
   * Only set on the 9 self-hosted hero images.
   */
  srcSet?: string;
  /** Author attribution (for the credit line). */
  author: string;
  /** Licence — CC BY-SA 4.0 / CC BY 3.0 / etc. */
  licence: string;
  /**
   * Link to the file's Commons page (auto-attribution back-link).
   * Optional — hero photos served self-hosted may still keep it for
   * the JSON-LD `creditText` field on /about.
   */
  commonsPage?: string;
};

/**
 * Build the responsive `srcSet` for a self-hosted hero WebP. The
 * widths (640 / 1080 / 1920 / 3840) mirror the variants generated by
 * scripts/perf/build-hero-webps.py during MSN-2975 chunk 1. The
 * descriptor unit `w` lets the browser pick the best variant from the
 * matching `sizes="100vw"` attribute on the consuming image.
 */
export function heroWebpSrcSet(slug: string): string {
  return [
    `/photos/hero-${slug}-640w.webp 640w`,
    `/photos/hero-${slug}-1080w.webp 1080w`,
    `/photos/hero-${slug}-1920w.webp 1920w`,
    `/photos/hero-${slug}-3840w.webp 3840w`,
  ].join(", ");
}

/** The default hero image URL (1920w variant — most common target). */
export function heroWebpUrl(slug: string): string {
  return `/photos/hero-${slug}-1920w.webp`;
}

export type CategoryPhotos = {
  /** Hero image — full-bleed at top of page. */
  hero: WikimediaPhoto;
  /** Inline images — distributed through the body sections. */
  inline: WikimediaPhoto[];
};

/* ----------------------------------------------------------------------
 * Hero images — 1 per category, picked by visual fit to the topic.
 * -------------------------------------------------------------------- */

const HERO = {
  surf: {
    caption: "Noosa Main Beach in late afternoon — the south-east swell wrapping past the headland.",
    url: heroWebpUrl("surf-and-weather"),
    srcSet: heroWebpSrcSet("surf-and-weather"),
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_03.jpeg",
  },
  noosaNationalPark: {
    caption: "The Noosa Headlands coastal walk — granite boulders, tallowwood forest, and the surf below.",
    url: heroWebpUrl("noosa-national-park"),
    srcSet: heroWebpSrcSet("noosa-national-park"),
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_and_Weyba_Creek.JPG",
  },
  accommodation: {
    caption: "Hastings Street storefronts and palms, looking toward Main Beach.",
    url: heroWebpUrl("accommodation"),
    srcSet: heroWebpSrcSet("accommodation"),
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Hastings_Street_Noosa_Heads,_Queensland.jpg",
  },
  thingsToDo: {
    caption: "Noosa Main Beach in December 2022 — the year-round swimming beach and the headland beyond.",
    url: heroWebpUrl("things-to-do"),
    srcSet: heroWebpSrcSet("things-to-do"),
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Beach,_Noosa_Heads,_Queensland,_2022.jpg",
  },
  fishingReports: {
    caption: "The Noosa River mouth, viewed from the headland — the principal recreational fishing water for the shire.",
    url: heroWebpUrl("fishing-reports"),
    srcSet: heroWebpSrcSet("fishing-reports"),
    author: "dronepicr",
    licence: "CC BY 2.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_(23720155369).jpg",
  },
  boatsAndWatercraft: {
    caption: "The Noosa Ferry at the Sofitel wharf — the river ferry is the easiest waterborne transport between Noosa Heads and Noosaville.",
    url: heroWebpUrl("boats-and-watercraft"),
    srcSet: heroWebpSrcSet("boats-and-watercraft"),
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Ferry_outside_Sofitel_Noosa_Pacific_Resort,_Noosa_Heads,_Queensland.jpg",
  },
  travelAndTransport: {
    caption: "Boardwalk along Noosa Main Beach — the short walk between Hastings Street and the Surf Club.",
    url: heroWebpUrl("travel-and-transport"),
    srcSet: heroWebpSrcSet("travel-and-transport"),
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Boardwalk_along_Noosa_Heads%E2%80%99_main_beach,_Queensland.jpg",
  },
  webcams: {
    caption: "Noosa Heads township and the river mouth — the drone view most live webcams approximate.",
    url: heroWebpUrl("webcams"),
    srcSet: heroWebpSrcSet("webcams"),
    author: "dronepicr",
    licence: "CC BY 3.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_(134205593).jpeg",
  },
} as const;

/* ----------------------------------------------------------------------
 * Inline images — 4 per category (3 minimum per Albert brief).
 * Each is placed between body sections in render order.
 * -------------------------------------------------------------------- */

const INLINE = {
  surf: [
    {
      caption: "Children learning to surf in the shallows at First Bay.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Children_learning_surfing_at_Noosa_Heads_beach%2C_Queensland.jpg/1280px-Children_learning_surfing_at_Noosa_Heads_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Children_learning_surfing_at_Noosa_Heads_beach,_Queensland.jpg",
    },
    {
      caption: "Early-morning paddle-out at Noosa Main Beach.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Noosa_Heads_beach_on_Christmas_Day_2015_04.jpeg/1280px-Noosa_Heads_beach_on_Christmas_Day_2015_04.jpeg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_04.jpeg",
    },
    {
      caption: "Stand-up paddleboarder in the bay — the calm-water alternative when the swell is too big.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg/1280px-Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Man_with_stand_up_board_at_Noosa_Heads_beach,_Queensland.jpg",
    },
    {
      caption: "The boardwalk along Noosa Main Beach — where most first-time surfers hire boards.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg/1280px-Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Boardwalk_along_Noosa_Heads%E2%80%99_main_beach,_Queensland.jpg",
    },
  ],
  noosaNationalPark: [
    {
      caption: "Foot-access-only beach along the Noosa headlands coastal walk.",
      url: "https://upload.wikimedia.org/wikipedia/commons/0/04/Noosa_head-raffi_kojian-CIMG6549.JPG",
      author: "Raffi Kojian",
      licence: "CC BY 2.5",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_head-raffi_kojian-CIMG6549.JPG",
    },
    {
      caption: "Aerial view of the headland and the river mouth.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Noosa_Heads_%2823720155369%29.jpg/1280px-Noosa_Heads_%2823720155369%29.jpg",
      author: "dronepicr",
      licence: "CC BY 2.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_(23720155369).jpg",
    },
    {
      caption: "A palm-silhouette evening view of Main Beach from the headland.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Noosa_Heads_beach_on_Christmas_Day_2015_01.jpeg/1280px-Noosa_Heads_beach_on_Christmas_Day_2015_01.jpeg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_01.jpeg",
    },
    {
      caption: "The Dog Beach at the Noosa Botanic Gardens on Lake Macdonald — a calmer inland option.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Dog_beach_at_Noosa_Botanic_Gardens.jpg/1280px-Dog_beach_at_Noosa_Botanic_Gardens.jpg",
      author: "Misaochan2",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Dog_beach_at_Noosa_Botanic_Gardens.jpg",
    },
  ],
  accommodation: [
    {
      caption: "French Quarter resort courtyard and pool.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/French_Quarter_resort%2C_Noosa_Heads.jpg/1280px-French_Quarter_resort%2C_Noosa_Heads.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:French_Quarter_resort,_Noosa_Heads.jpg",
    },
    {
      caption: "Maison Noosa Resort entrance — one of the Hastings Street properties.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Maison_Noosa_Resort.jpg/1280px-Maison_Noosa_Resort.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Maison_Noosa_Resort.jpg",
    },
    {
      caption: "Holiday resort overlooking Noosa Main Beach.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Holiday_resort_on_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg/1280px-Holiday_resort_on_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Holiday_resort_on_Noosa_Heads%E2%80%99_main_beach,_Queensland.jpg",
    },
    {
      caption: "Noosa Harbour Resort, on the Noosaville waterfront.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Noosa_Harbour_Resort.jpg/1280px-Noosa_Harbour_Resort.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Harbour_Resort.jpg",
    },
  ],
  thingsToDo: [
    {
      caption: "The Boardwalk along Main Beach — the 800 m walk from Hastings Street to the Surf Club.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg/1280px-Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Boardwalk_along_Noosa_Heads%E2%80%99_main_beach,_Queensland.jpg",
    },
    {
      caption: "Latte art on a Hastings Street café table — the headland end of Noosa Main Beach in the background.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Aromas_Latte_art%2C_Noosa_Heads%2C_Queensland.jpg/1280px-Aromas_Latte_art%2C_Noosa_Heads%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Aromas_Latte_art,_Noosa_Heads,_Queensland.jpg",
    },
    {
      caption: "Noosa Farmers Market — Sunday morning on the Noosaville showgrounds.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Noosa_farmers_market.jpg/1280px-Noosa_farmers_market.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_farmers_market.jpg",
    },
    {
      caption: "Stand-up paddleboarder in the bay.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg/1280px-Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Man_with_stand_up_board_at_Noosa_Heads_beach,_Queensland.jpg",
    },
  ],
  fishingReports: [
    {
      caption: "The Noosa River at low tide — the principal fishing water for bream, flathead, and whiting.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Noosa_Heads_beach_in_January_2015.JPG/1280px-Noosa_Heads_beach_in_January_2015.JPG",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_in_January_2015.JPG",
    },
    {
      caption: "Long beach panorama from the headland — the gutters on the southern end hold tailor and dart.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Noosa_Heads_beach_on_Christmas_Day_2015_05.jpeg/1280px-Noosa_Heads_beach_on_Christmas_Day_2015_05.jpeg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_05.jpeg",
    },
    {
      caption: "Child building a sandcastle at Noosa Main Beach — the weekday rhythm of the lagoon.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Artis_building_a_sand_castle_at_Noosa_Heads_beach%2C_Queensland_in_November_2016.jpg/1280px-Artis_building_a_sand_castle_at_Noosa_Heads_beach%2C_Queensland_in_November_2016.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Artis_building_a_sand_castle_at_Noosa_Heads_beach,_Queensland_in_November_2016.jpg",
    },
    {
      caption: "Newlyweds on Noosa Main Beach, February 2017 — the bay at its calmest.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Newlyweds_at_Noosa_Heads_Main_Beach_02.2017%2C_01.jpg/1280px-Newlyweds_at_Noosa_Heads_Main_Beach_02.2017%2C_01.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Newlyweds_at_Noosa_Heads_Main_Beach_02.2017,_01.jpg",
    },
  ],
  boatsAndWatercraft: [
    {
      caption: "Noosa Heads township and the river mouth — the bar opens south-east of the headland.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Noosa_Heads_%28134205593%29.jpeg/1280px-Noosa_Heads_%28134205593%29.jpeg",
      author: "dronepicr",
      licence: "CC BY 3.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_(134205593).jpeg",
    },
    {
      caption: "Stand-up paddleboarder on the bay — the paddle craft most commonly hired in Noosa.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg/1280px-Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Man_with_stand_up_board_at_Noosa_Heads_beach,_Queensland.jpg",
    },
    {
      caption: "The Boardwalk along Main Beach — where most river-bound tour boats stage.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg/1280px-Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Boardwalk_along_Noosa_Heads%E2%80%99_main_beach,_Queensland.jpg",
    },
    {
      caption: "The Noosa River at low tide, viewed from the headland.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Noosa_Heads_and_Weyba_Creek.JPG/1280px-Noosa_Heads_and_Weyba_Creek.JPG",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_and_Weyba_Creek.JPG",
    },
  ],
  travelAndTransport: [
    {
      caption: "Noosa Heads township and the Bruce Highway approach, viewed from the headland.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Noosa_Heads_%28134205593%29.jpeg/1280px-Noosa_Heads_%28134205593%29.jpeg",
      author: "dronepicr",
      licence: "CC BY 3.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_(134205593).jpeg",
    },
    {
      caption: "Mobile coffee van, Australian coast — a frequent sight at the Noosa North Shore campgrounds.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Mobile_coffee_van_in_Australia.jpg/1280px-Mobile_coffee_van_in_Australia.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 3.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Mobile_coffee_van_in_Australia.jpg",
    },
    {
      caption: "Campervan on the Coast — the road-trip mode into Noosa.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Camper_Wohnmobil_Australien_%2823979876582%29.jpg/1280px-Camper_Wohnmobil_Australien_%2823979876582%29.jpg",
      author: "Kgbo",
      licence: "CC BY 2.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Camper_Wohnmobil_Australien_(23979876582).jpg",
    },
    {
      caption: "The Noosa Ferry at the Sofitel wharf — waterborne transport between Noosa Heads and Noosaville.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Noosa_Ferry_outside_Sofitel_Noosa_Pacific_Resort%2C_Noosa_Heads%2C_Queensland.jpg/1280px-Noosa_Ferry_outside_Sofitel_Noosa_Pacific_Resort%2C_Noosa_Heads%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Ferry_outside_Sofitel_Noosa_Pacific_Resort,_Noosa_Heads,_Queensland.jpg",
    },
  ],
  webcams: [
    {
      caption: "Noosa Main Beach at midday, viewed from the headland.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Noosa_Heads_beach_in_January_2015.JPG/1280px-Noosa_Heads_beach_in_January_2015.JPG",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_in_January_2015.JPG",
    },
    {
      caption: "Long beach panorama — the angle most of the public webcams capture.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Noosa_Heads_beach_on_Christmas_Day_2015_05.jpeg/1280px-Noosa_Heads_beach_on_Christmas_Day_2015_05.jpeg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_05.jpeg",
    },
    {
      caption: "Aerial of the river mouth — used by the Council coastal-cams overview.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Noosa_Heads_%28134205593%29.jpeg/1280px-Noosa_Heads_%28134205593%29.jpeg",
      author: "dronepicr",
      licence: "CC BY 3.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_(134205593).jpeg",
    },
    {
      caption: "The Boardwalk along Main Beach — the camera position of most foot-traffic webcams.",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg/1280px-Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg",
      author: "Kgbo",
      licence: "CC BY-SA 4.0",
      commonsPage: "https://commons.wikimedia.org/wiki/File:Boardwalk_along_Noosa_Heads%E2%80%99_main_beach,_Queensland.jpg",
    },
  ],
} as const;

/* ----------------------------------------------------------------------
 * Export — every category slug maps to its photo set.
 * -------------------------------------------------------------------- */

export const CATEGORY_PHOTOS: Record<string, CategoryPhotos> = {
  "surf-and-weather": { hero: HERO.surf, inline: [...INLINE.surf] },
  "noosa-national-park": {
    hero: HERO.noosaNationalPark,
    inline: [...INLINE.noosaNationalPark],
  },
  accommodation: { hero: HERO.accommodation, inline: [...INLINE.accommodation] },
  "things-to-do": { hero: HERO.thingsToDo, inline: [...INLINE.thingsToDo] },
  "fishing-reports": {
    hero: HERO.fishingReports,
    inline: [...INLINE.fishingReports],
  },
  "boats-and-watercraft": {
    hero: HERO.boatsAndWatercraft,
    inline: [...INLINE.boatsAndWatercraft],
  },
  "travel-and-transport": {
    hero: HERO.travelAndTransport,
    inline: [...INLINE.travelAndTransport],
  },
  webcams: { hero: HERO.webcams, inline: [...INLINE.webcams] },
};

/* ----------------------------------------------------------------------
 * Homepage hero — MSN-2972 aspirational upgrade.
 *
 * Compared the MSN-2965 hero (January 2015 golden-hour Main Beach with
 * walker) against three new sunset candidates. The April 2020 sunset
 * over the actual beach (headland silhouetted, palm in foreground,
 * sand-and-water texture) wins on:
 *   - real sunset light (not golden-hour) — destination-mood setter
 *   - headland silhouette in the upper third (geographic signature)
 *   - foreground palm-frond provides natural framing for overlay
 *   - 3948×2961 px source — high enough for 2K rendering
 * Avoids the township drone and the existing "By the headland, by the
 * bar" tonal register.
 *
 * Credits: Kgbo / Wikimedia Commons · CC BY-SA 4.0.
 * -------------------------------------------------------------------- */

export const HOMEPAGE_HERO: WikimediaPhoto = {
  caption:
    "Sunset over Noosa Main Beach, April 2020 — headland silhouette, palm frond and the long beach.",
  url: heroWebpUrl("home"),
  srcSet: heroWebpSrcSet("home"),
  author: "Kgbo",
  licence: "CC BY-SA 4.0",
  commonsPage:
    "https://commons.wikimedia.org/wiki/File:Sunset_over_Noosa_Beach,_Noosa_Heads,_Queensland_04.jpg",
};

/* ----------------------------------------------------------------------
 * MSN-2972 — six image-led homepage tiles.
 *
 * Each tile gets a single aspirational Wikimedia Commons image. The
 * "Where to stay" tile is intentionally the strongest (Hastings Street
 * 2022, the highest-resolution, golden-hour, palm-lined, walk-up to the
 * headland). The other tiles are chosen for topic fit + visual variety.
 *
 * Each photo URL is a 1280-px upload.wikimedia.org thumbnail, which
 * next/image can transform (see next.config.mjs remotePatterns).
 * -------------------------------------------------------------------- */

export const HOME_TILES = {
  /** Strongest commercial — Hastings Street looking up to the headland. */
  whereToStay: {
    caption:
      "Hastings Street looking up to the headland — the walk from a Hastings Street hotel to Main Beach.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Hastings_Street%2C_Noosa_Heads%2C_Queensland%2C_2022%2C_03.jpg/1280px-Hastings_Street%2C_Noosa_Heads%2C_Queensland%2C_2022%2C_03.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage:
      "https://commons.wikimedia.org/wiki/File:Hastings_Street,_Noosa_Heads,_Queensland,_2022,_03.jpg",
  },
  /** Noosa River calm water — alternative to surf. */
  thingsToDo: {
    caption:
      "The Noosa River at Noosaville, looking downstream — paddleboard and kayak water.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Noosa_River_bank_at_Noosaville%2C_Queensland%2C_2024.jpg/1280px-Noosa_River_bank_at_Noosaville%2C_Queensland%2C_2024.jpg",
    author: "Chris Olszewski",
    licence: "CC BY-SA 4.0",
    commonsPage:
      "https://commons.wikimedia.org/wiki/File:Noosa_River_bank_at_Noosaville,_Queensland,_2024.jpg",
  },
  /** Beaches & nature — headland view from the coastal walk. */
  beachesAndNature: {
    caption:
      "The Noosa headland and the river mouth — the coastal walk's signature view.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Noosa_Heads_and_Weyba_Creek.JPG/1280px-Noosa_Heads_and_Weyba_Creek.JPG",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage:
      "https://commons.wikimedia.org/wiki/File:Noosa_Heads_and_Weyba_Creek.JPG",
  },
  /** Eat & drink — Hastings Street café table with the beach in view. */
  eatAndDrink: {
    caption:
      "A Hastings Street café table with the headland and Main Beach in the background.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Aromas_Latte_art%2C_Noosa_Heads%2C_Queensland.jpg/1280px-Aromas_Latte_art%2C_Noosa_Heads%2C_Queensland.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage:
      "https://commons.wikimedia.org/wiki/File:Aromas_Latte_art,_Noosa_Heads,_Queensland.jpg",
  },
  /** Plan your trip — the Noosa Ferry, river-borne transport. */
  planYourTrip: {
    caption:
      "The Noosa Ferry at the Sofitel wharf — the easiest waterborne transport between Hastings Street and Noosaville.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Noosa_Ferry_outside_Sofitel_Noosa_Pacific_Resort%2C_Noosa_Heads%2C_Queensland.jpg/1280px-Noosa_Ferry_outside_Sofitel_Noosa_Pacific_Resort%2C_Noosa_Heads%2C_Queensland.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage:
      "https://commons.wikimedia.org/wiki/File:Noosa_Ferry_outside_Sofitel_Noosa_Pacific_Resort,_Noosa_Heads,_Queensland.jpg",
  },
  /** Today in Noosa — Main Beach on a sunny day. */
  todayInNoosa: {
    caption:
      "Noosa Main Beach on a sunny day — the live surf and weather destination for the homepage live strip.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Noosa_Heads_beach_on_Christmas_Day_2015_03.jpeg/1280px-Noosa_Heads_beach_on_Christmas_Day_2015_03.jpeg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage:
      "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_03.jpeg",
  },
} as const;

/** Inspirational feature image — sunrise over Laguna Bay from headland. */
export const FEATURE_IMAGE: WikimediaPhoto = {
  caption:
    "Sunrise over Laguna Bay from the Noosa headland coastal walk.",
  url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Noosa_Heads_beach.jpg/1280px-Noosa_Heads_beach.jpg",
  author: "Renee Whelan",
  licence: "CC BY-SA 4.0",
  commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach.jpg",
};

/* ----------------------------------------------------------------------
 * MSN-2972 — twelve /things-to-do category images.
 *
 * One image per category card, mapped to the D2 category list. Each
 * image is verified on Commons (Kwbo / Chris Olszewski / dronepicr)
 * and uses the same upload.wikimedia.org 1280-px thumbnail convention
 * as the rest of the photo set.
 * -------------------------------------------------------------------- */

export const CATEGORY_CARD_PHOTOS = {
  bestBeaches: {
    caption: "Noosa Main Beach at midday — the patrolled swimming beach at the bottom of Hastings Street.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Noosa_Heads_beach_on_Christmas_Day_2015_03.jpeg/1280px-Noosa_Heads_beach_on_Christmas_Day_2015_03.jpeg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_03.jpeg",
  },
  walksAndNature: {
    caption: "The Noosa headland coastal walk — granite boulders, tallowwood forest, the surf below.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Noosa_Heads_and_Weyba_Creek.JPG/1280px-Noosa_Heads_and_Weyba_Creek.JPG",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_and_Weyba_Creek.JPG",
  },
  riverAdventures: {
    caption: "The Noosa River at Noosaville — kayak and paddleboard water.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Noosa_River_bank_at_Noosaville%2C_Queensland%2C_2024.jpg/1280px-Noosa_River_bank_at_Noosaville%2C_Queensland%2C_2024.jpg",
    author: "Chris Olszewski",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_River_bank_at_Noosaville,_Queensland,_2024.jpg",
  },
  foodAndDrink: {
    caption: "A Hastings Street café table — latte and the headland beyond.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Aromas_Latte_art%2C_Noosa_Heads%2C_Queensland.jpg/1280px-Aromas_Latte_art%2C_Noosa_Heads%2C_Queensland.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Aromas_Latte_art,_Noosa_Heads,_Queensland.jpg",
  },
  surfingAndWaterSports: {
    caption: "Early-morning paddle-out at Noosa Main Beach — the calm-water option when the swell is up.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Noosa_Heads_beach_on_Christmas_Day_2015_04.jpeg/1280px-Noosa_Heads_beach_on_Christmas_Day_2015_04.jpeg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_beach_on_Christmas_Day_2015_04.jpeg",
  },
  familyActivities: {
    caption: "Children learning to surf in the shallows at First Bay.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Children_learning_surfing_at_Noosa_Heads_beach%2C_Queensland.jpg/1280px-Children_learning_surfing_at_Noosa_Heads_beach%2C_Queensland.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Children_learning_surfing_at_Noosa_Heads_beach,_Queensland.jpg",
  },
  wellnessAndRelaxation: {
    caption: "Boardwalk along Main Beach — the short walk between Hastings Street and the Surf Club.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg/1280px-Boardwalk_along_Noosa_Heads%E2%80%99_main_beach%2C_Queensland.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Boardwalk_along_Noosa_Heads%E2%80%99_main_beach,_Queensland.jpg",
  },
  marketsAndShopping: {
    caption: "Noosa Farmers Market — Sunday morning on the Noosaville showgrounds.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Noosa_farmers_market.jpg/1280px-Noosa_farmers_market.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_farmers_market.jpg",
  },
  dayTrips: {
    caption: "A camper on the Coast — the road-trip mode into the Noosa Hinterland.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Camper_Wohnmobil_Australien_%2823979876582%29.jpg/1280px-Camper_Wohnmobil_Australien_%2823979876582%29.jpg",
    author: "Kgbo",
    licence: "CC BY 2.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Camper_Wohnmobil_Australien_(23979876582).jpg",
  },
  rainyDay: {
    caption: "Hastings Street in soft overcast light — the rainy-day walk.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Hastings_Street_Noosa_Heads%2C_Queensland.jpg/1280px-Hastings_Street_Noosa_Heads%2C_Queensland.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Hastings_Street_Noosa_Heads,_Queensland.jpg",
  },
  bookableExperiences: {
    caption: "Stand-up paddleboarder in the bay — the hire-watercraft most visitors start with.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg/1280px-Man_with_stand_up_board_at_Noosa_Heads_beach%2C_Queensland.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Man_with_stand_up_board_at_Noosa_Heads_beach,_Queensland.jpg",
  },
  itineraries: {
    caption: "Sunset over Noosa Beach — the headline image for first-time visitor itineraries.",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Sunset_over_Noosa_Beach%2C_Noosa_Heads%2C_Queensland_04.jpg/1280px-Sunset_over_Noosa_Beach%2C_Noosa_Heads%2C_Queensland_04.jpg",
    author: "Kgbo",
    licence: "CC BY-SA 4.0",
    commonsPage: "https://commons.wikimedia.org/wiki/File:Sunset_over_Noosa_Beach,_Noosa_Heads,_Queensland_04.jpg",
  },
} as const;

/* ----------------------------------------------------------------------
 * /about brand-statement masthead image — quieter, more editorial
 * (granite headland + boardwalk rather than the swimming beach).
 * -------------------------------------------------------------------- */

export const ABOUT_BRAND_IMAGE: WikimediaPhoto = {
  caption: "The granite headland and the Weyba Creek confluence, viewed from the coastal walk.",
  url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Noosa_Heads_and_Weyba_Creek.JPG/1280px-Noosa_Heads_and_Weyba_Creek.JPG",
  author: "Kgbo",
  licence: "CC BY-SA 4.0",
  commonsPage: "https://commons.wikimedia.org/wiki/File:Noosa_Heads_and_Weyba_Creek.JPG",
};
